### ISSUE TITLE
Routes regexps support

### ISSUE THREAD

**Issue by Igloczek** [krasimir/now-lambda-runner#1]
Seems like you are currently not supporting the same format of describing route source as Now itself.

In my case, this throws errors trying to run locally, but work perfectly fine on Now:
```json
"routes": [
    { "src": "/api/entity/(?<name>[^/]*)", "dest": "/api/entity.js?name=$name" },
    { "src": "/api/collection/(?<name>[^/]*)", "dest": "/api/collection.js?name=$name" }
],
```

Docs: https://zeit.co/docs/v2/deployments/configuration/#routes

Stacktrace:
```
/Users/igloczek/.nvm/versions/node/v8.11.3/lib/node_modules/now-lambda-runner/index.js:43
    const r = new RegExp(route.src);
              ^

SyntaxError: Invalid regular expression: //api/entity/(?<name>[^/]*)/: Invalid group
    at new RegExp (<anonymous>)
    at nowConf.routes.forEach.route (/Users/igloczek/.nvm/versions/node/v8.11.3/lib/node_modules/now-lambda-runner/index.js:43:15)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/Users/igloczek/.nvm/versions/node/v8.11.3/lib/node_modules/now-lambda-runner/index.js:39:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
```

**Comment by krasimir** [comment]
Good spot. I thought that now uses regular regular expressions :) It looks like that is not the case. I'll have to dig a little bit to see how how resolve the URL.

**Comment by krasimir** [comment]
In the meantime maybe:
```
"routes": [
    { "src": "/api/entity/(.*)", "dest": "/api/entity.js?name=$1" },
    { "src": "/api/collection/(.*)", "dest": "/api/collection.js?name=$1" }
]
```

**Comment by krasimir** [comment]
@Igloczek can you please try the latest `1.0.0` version. It should work now. I tested with the following:
```json
"routes": [
    { "src": "/e/resources/(?<resource>[^/]*)", "dest": "/www/static/app/resources/$resource"}
  ]
```

**Comment by pungggi** [comment]
hi @krasimir 
I tried version 1.
It seems like it matches but then does not resolve?

![grafik](https://user-images.githubusercontent.com/5635709/49782687-827b6480-fd17-11e8-9402-c9485a4c6edd.png)


![grafik](https://user-images.githubusercontent.com/5635709/49782669-742d4880-fd17-11e8-8024-fe7caf42f7c7.png)

**Comment by krasimir** [comment]
Just released 1.1.0 and should be ok ;)
I have:
```json
{ "src": "/api/(?<resource>[^/]*)", "dest": "/api/$resource/index.js?name=$resource" },
```
And the following `/api/test/index.js` file:
```js
const { parse } = require('url');

module.exports = (req, res) => {
  const { query } = parse(req.url, true);
  res.send('hello world ' + query.name);
}
```
The result for the http://localhost:8004/api/test is 
![image](https://user-images.githubusercontent.com/528677/49803307-1bca6b00-fd58-11e8-8e39-4da59b0d4121.png)
![image](https://user-images.githubusercontent.com/528677/49803328-27b62d00-fd58-11e8-88c9-0f05108c44c5.png)

**Comment by pungggi** [comment]
ah nice! thank you very useful

**Comment by krasimir** [comment]
@Igloczek is the latest version working for you?

**Comment by Igloczek** [comment]
It doesn't throw errors about routes syntax, so I can assume it works, but something else doesn't work for me... If I found what is wrong will let you know, maybe it's just something on my side.
